services:
  mariadb:
    image: mariadb:11.7.2
    container_name: mariadb_container
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mariadb", "-u", "root", "--password=${MARIADB_ROOT_PASSWORD}", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  python-app:
    image: python-app-image # name the image
    build:
      # Directory containing build context (Dockerfile and source files)
      context: ./python-app
      # Name of the Dockerfile to use (could be omitted if named "Dockerfile")
      dockerfile: Dockerfile
    container_name: python_app_container
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
    name: mariadb_data_volume
