services:
  mariadb:
    image: mariadb:11.7.2
    container_name: mariadb_container
    ports:
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    name: mariadb_data_volume
